# ePims Client local overrides
# Any value defined here will override the values retrieved from the server when applicable.
#
# FTP/SFTP connection overrides
# If set, this host will be used instead of the one returned by the server.
#ftp.host=
# Optional SFTP port (defaults to 22 if not set)
#ftp.port=22

# Path to the private key used for SFTP authentication.
# Default is ./config/epims-id_rsa next to the distribution.
# You can use an absolute path if desired.
#ftp.keyPath=./config/epims-id_rsa
